[package]
name = "pyembed-runner"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
anyhow = "1"
pyo3 = { version = "0.23", features = ["auto-initialize"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tar = "0.4"
zstd = "0.13"
dirs = "5"

[build-dependencies]
anyhow = "1"
walkdir = "2"
